# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-25 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20190125_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='users',
            field=models.ManyToManyField(related_name='trips', to='first_app.User'),
        ),
    ]
