# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-25 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20190125_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='users',
        ),
        migrations.AddField(
            model_name='trips',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='first_app.User'),
            preserve_default=False,
        ),
    ]
