# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-25 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20190125_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='users',
            new_name='user',
        ),
    ]
