# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-25 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_auto_20190125_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trips',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
